JAVA_SRC = Agent.java ASMModelParams.java ASMModelSwarm.java ASMObserverSwarm.java BFagent.java BFCast.java  BFParams.java  BitName.java  BitVector.java  Dividend.java  KeyTable.java MovingAverage.java Output.java Parameters.java Specialist.java  StartASM.java  World.java     

all: $(JAVA_SRC)
	$(SWARMHOME)/bin/javacswarm $(JAVA_SRC)

clean: 
	rm -f *.class







