#!/bin/sh -e

TMP=version.m.old

cp version.m $TMP

eval `sed -e '/^#define VERSIONNUMBER/!d' \
	-e 's/.*"\(.*\)\./MAJOR="\1"; MINOR=/' -e 's/"$//' $TMP`
MINOR=`expr $MINOR + 1`
echo "Version $MAJOR.$MINOR"

sed -e '
/^#define VERSIONNUMBER/s/".*"/"'"$MAJOR.$MINOR"'"/
' $TMP > version.m

rm -f $TMP

